// Menu-bar icon and menu. Uses a Template image so macOS tints it for light/dark menu bars.
const path = require('path');
const { Tray, Menu, nativeImage } = require('electron');

function createTray(actions) {
  // trayTemplate.png + trayTemplate@2x.png — black + alpha only (generated by scripts/make-icon.js)
  const icon = nativeImage.createFromPath(path.join(__dirname, 'assets', 'trayTemplate.png'));
  icon.setTemplateImage(true);
  const tray = new Tray(icon.isEmpty() ? nativeImage.createEmpty() : icon);
  if (icon.isEmpty()) tray.setTitle('J');
  tray.setToolTip('Jarvis');

  const rebuild = (state) => {
    const menu = Menu.buildFromTemplate([
      { label: 'Jarvis', enabled: false },
      { type: 'separator' },
      {
        label: state.orbVisible ? 'Hide orb' : 'Show orb',
        accelerator: 'Command+Option+H',
        click: () => actions.toggleOrb(),
      },
      {
        label: state.hudOpen ? 'Minimize to orb' : 'Show Jarvis',
        accelerator: 'Command+Option+U',
        click: () => actions.toggleHud(),
      },
      { label: 'Settings…', accelerator: 'Command+Option+P', click: () => actions.openPanel('settings') },
      { type: 'separator' },
      {
        label: 'Mute microphone',
        type: 'checkbox',
        checked: state.micMuted,
        click: (item) => actions.setMicMuted(item.checked),
      },
      {
        label: 'Open at login',
        type: 'checkbox',
        checked: state.startWithSystem,
        click: (item) => actions.setStartWithSystem(item.checked),
      },
      { type: 'separator' },
      { label: 'Restart engine', click: () => actions.restartEngine() },
      { label: 'Open logs folder', click: () => actions.openLogs() },
      { type: 'separator' },
      { label: 'Quit Jarvis', accelerator: 'Command+Q', click: () => actions.quit() },
    ]);
    // On macOS a click on the menu-bar icon opens this menu.
    tray.setContextMenu(menu);
  };

  return { tray, rebuild };
}

module.exports = { createTray };
